config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'horses#search'
  resources :horses do
    resources :bookings, only: [:new, :create]
  end
  get "/dashboard", to: "dashboard#show"
  patch "/bookings/:id", to: "bookings#confirm_booking", as: 'confirm_booking'
  # patch "/bookings/:id", to: "bookings#reject_booking", as: 'reject_booking'
  get "/search", to: "horses#search"
  resources :bookings, only: [:show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :horse
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true
end

app/models/horse.rb
class Horse < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :price, presence: true
  validates :description, presence: true
  # validates :image, presence: true
  mount_uploader :image, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :horses, dependent: :destroy
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || search_path
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy, :confirm_booking, :reject_booking]

  def index
    @bookings = Booking.all
  end

  def show
    horse = @booking.horse
    @markers = [{ lat: horse.latitude, lng: horse.longitude }]
  end

  def create
    @horse = Horse.find(params[:horse_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.horse = @horse
    @booking.total_price = @horse.price * (@booking.end_date - @booking.start_date)
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render template: 'horses/show'
    end
  end

  # def edit
  # end

  def confirm_booking
    if @booking.status == "pending"
      if params[:status] == "accept"
        @booking.status = "Accepted"
      elsif params[:status] == "reject"
        @booking.status = "Rejected"
      end
      @booking.save
    end
    redirect_to dashboard_path
  end

  def reject_booking
    @booking.status = "rejected"
    @booking.save
    redirect_to dashboard_path
  end

  def destroy
    @booking.destroy
    redirect_to root_path
  end

  private

  def status
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @horses = Horse.where(user: current_user)
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :set_horse, only: [:show, :edit, :update, :destroy]

  def markers(horses)
    @markers = horses.map do |horse|
      {
        lat: horse.latitude,
        lng: horse.longitude
        # infoWindow: render_to_string(partial: "infowindow", locals: { flat: flat }),
        # image_url: helpers.asset_url('icon-img.png')
      }
    end
  end

  def index
    if params[:query].present?
      # sql_query = "location @@ :query OR description @@ :query"
      # @horses = Horse.geocoded
      @horses = Horse.near(params[:query], 25)
    else
      @horses = Horse.all
    end
    markers(@horses)
  end

  def show
    @markers = [{ lat: @horse.latitude, lng: @horse.longitude }]
    @booking = Booking.new
  end

  def search
    @horse = Horse.new
  end

  def new
    @horse = Horse.new
  end

  def create
    @horse = Horse.new(horse_params)
    @horse.user = current_user
    if @horse.save
      redirect_to horse_path(@horse)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @horse.update(horse_params)
      redirect_to horse_path(@horse)
    else
      render :edit
    end
  end

  def destroy
    @horse.destroy
    redirect_to dashboard_path
  end

  private

  def set_horse
    @horse = Horse.find(params[:id])
  end

  def horse_params
    params.require(:horse).permit(:name, :location, :price, :description, :image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
-<div class="booking-message">
  <p>
  <% if @booking.status == "pending"  %>
    <p class="booking-pending">Your booking is <%= @booking.status %></p>
  <% elsif @booking.status == "Accepted" %>
    <p class="booking-accepted">Your booking is <%= @booking.status %></p>
  <% else @booking.status == "Rejected" %>
    <p class="booking-rejected">Your booking is <%= @booking.status %></p>
  <% end %>
   <div class="text-center"> <strong>You can see the details of your booking in your dashboard.</strong></div>
 </p>
</div>
<div class="banner" style="background-image: url('<%= cl_image_path @booking.horse.image, crop: :scale %>')">
</div>

<div class="container d-flex mt-3">
  <div class="booking-info">
    <h3>Booking details</h3>
    <br>
    <h6 style="line-height: 0;"> Booking Start Date </h6>
    <p><%= @booking.start_date %></p>
    <h6 style="line-height: 0;"> Booking End Date </h6>
    <p><%= @booking.end_date %></p>
    <h6 style="line-height: 0;"> Horse</h6>
     <p> <%= @booking.horse.name %></p>
    <h6 style="line-height: 0;">Owner</h6>
    <p><%= @booking.horse.user.email %></p>
    <h6> Total price <strong><%= @booking.total_price %> €</strong></h6>
  </div>

  <div class="container content-container">
    <div class="location-title mb-2 ">
      <h6>Stationed in
        <%= @booking.horse.location %></h6>
    </div>
          <%#= image_tag "https://s3.eestatic.com/2017/10/11/social/La_Jungla_253487245_50033619_1024x576.jpg", alt: "map", class: "map mt-4" %>
          <!--       <p class="mt-2">Exact location information is provided after a booking is confirmed.</p> -->
          <div
          id="map" class="show-map"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
</div>













<!--



  <div class="container content-container">
    <div class="infos mt-2">

      <h1><strong><%= @booking.horse.name %></strong></h1>
      <br>
       <div class="booking-info">
        <h3>Booking summary:</h3>
        <h5> Booking Start Date: <%= @booking.start_date %></h5>
        <h5> Booking End Date: <%= @booking.end_date %></h5>
        <br>
        <h5> Total Price: <strong><%= @booking.total_price %> €</strong></h5>
      </div>
      <%= link_to 'Delete Booking', booking_path(@booking), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-delete"%>
      <div class="info-perso">
        <div>
          <h4><strong>Owner</strong></h4>
          <p><%= @booking.horse.user.email %></p>
        </div>
      </div>
      <div>
        <h4><strong>Description</strong></h4>
        <p><%= @booking.horse.description %></p>
        <h4><strong>Price</strong></h4>
        <p><%= @booking.horse.price %> € / day</p>
      </div>
    <div
      id="map" class="show-map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>



 -->

app/views/dashboard/show.html.erb
<div class="container">
  <h3 class="header-dashboard">Your listings</h3>
  <div class="listings">
    <% @horses.each do |horse| %>
      <div class="card-listing">
        <%= cl_image_tag horse.image, crop: :fill %>
        <div class="card-listing-infos">
            <h4 class="horse-name" style="line-height: 0;"><%= link_to horse.name, horse_path(horse) %></h4>
            <p>Bookings</p>
              <% if @bookings.nil? %>
                <p>no booking</p>
              <% else %>
                <% horse.bookings.last(3).each do |booking| %>
                <div class="horse-booking-info d-flex justify-content-between">
                  <div class="infos-horse-booking d-flex justify-content-between">
                    <p class="infos-horse-booking-withoutstatus">
                      <%= booking.start_date.strftime("%b %e %Y") %>
                      <%= booking.end_date %>,
                      <%= booking.user.email %>,
                      <%= booking.total_price %> €
                      <% if booking.status == "pending"  %>
                        <p class="booking-pending"><%= booking.status %></p>
                      <% elsif booking.status == "Accepted" %>
                        <p class="booking-accepted"><%= booking.status %></p>
                      <% else booking.status == "Rejected" %>
                        <p class="booking-rejected"><%= booking.status %></p>
                      <% end %>
                    </p>

                  </div>
                  <div class="status-buttons">
                    <p>
                      <%= link_to 'Accept', confirm_booking_path(booking, status: 'accept'), method: :patch, action: :confirm_booking %>
                      <%= link_to 'Reject', confirm_booking_path(booking, status: 'reject'), method: :patch, action: :confirm_booking %>
                    </p>
                  </div>
                </div>

                  <br>
                <%end %>
              <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <h3 class="header-dashboard">Your bookings</h3>
  <div class="bookings">
    <%if @bookings.nil? %>
      <p>normal</p>
    <% else %>
    <div class="cards-booking">
      <% @bookings.each do |booking| %>
        <div class="card-booking">
          <%= cl_image_tag booking.horse.image, crop: :fill %>
          <div class="card-bookingss-infos">
            <h2 class="horse-name-booking"><%= link_to booking.horse.name, booking_path(booking) %></h2>

            <p class="booking-date-mine">
            <%= booking.start_date %>
            <%= booking.end_date %></p>
            <p class="booking-price-mine"><%= booking.total_price %> €</p>
            <% if booking.status == "pending"  %>
              <p class="booking-pending"><%= booking.status %></p>
            <% elsif booking.status == "Accepted" %>
              <p class="booking-accepted"><%= booking.status %></p>
            <% else booking.status == "Rejected" %>
              <p class="booking-rejected"><%= booking.status %></p>
            <% end %>
          </div>
        </div>
      <%end %>
    </div>

    <% end %>
  </div>

</div>

app/views/horses/_form.html.erb
<div class="simpleform p-3">
  <%= simple_form_for @horse do |f| %>
  <%= f.input :name, label_html: { class: "formlabel" } %>
  <%= f.input :location, label: "Address", label_html: { class: "formlabel" }  %>
  <%= f.input :price, label: "Price €", label_html: { class: "formlabel" }  %>
  <%= f.input :description, label_html: { class: "formlabel" }  %>
  <div class="d-flex justify-content-center">
    <%= f.input :image, label_html: { class: "formlabel" }  %>
    <%= f.input :image_cache, as: :hidden, label_html: { class: "formlabel" }  %>
    <div class="mt-4"style="height: 40px;">
      <%= f.button :submit, class: "btn btn-info"%>
      <% end %>
    </div>
  </div>
</div>

app/views/horses/_searchform.html.erb
<div class="wrapper-container">
  <div class="simpleform">
    <div class="search-container" style="width: 500px; margin-top: 95px;">
      <h1 class="mb-4" style="color: black; text-shadow: 1px 1px grey;">Get started and rent a horse close to you today.</h1>
      <div class="search-form-control form-group">
        <%= form_tag horses_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control",
          placeholder: "Location"%>
          <button name="button" type="submit" class="btn btn-flat">
            <i class="fas fa-search"></i> Search
          </button>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/horses/edit.html.erb
<div class="background-edit">
<div class="container edit-horse">
    <div class="wrapper-form p-3 mt-5" style="width: 400px;">
      <h3>Edit your horse</h3>
      <%= render 'form', horse: @horse %>
    </div>
</div>
</div>

app/views/horses/index.html.erb
<div class="whole-thing">
  <div class="left side">
    <div class="top-bit">
      <% if @horses.empty? %>
        <p id="search-message">Found no horses near <%= params[:query] %>.</p>
      <% elsif params[:query].present? %>
        <p id="search-message">Horses near <%= params[:query] %>...</p>
      <% end %>
    </div>
    <!-- <div class="cards-container"> -->
      <div class="cards">
        <% @horses.each do |horse| %>
          <div class="card">
            <%= link_to horse_path(horse) do %>
              <%= cl_image_tag horse.image, height: 150 %>
            <% end %>
              <div class="card-details mt-2">
                <div class="card-left">
                  <h5><%= horse.name %></h5>
                  <h5 class="address" style="color: rgb(72, 72, 72); line-height: 1;"><small><%= horse.location %></small></h5>
                </div>
                <div class="price">
                  <h5 style="color: rgb(72, 72, 72);"><small><%= horse.price %>€</small></h5>
                </div>
              </div>
          </div>
        <% end %>
      </div>
    <!-- </div> -->
  </div>
  <div
    id="map" class="results-map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/horses/new.html.erb
<div class="wrapper wrapper-search p-5" style="background-image: url(<%= image_path 'horsecute.jpg' %>)">
    <div class="wrapper-form p-3 ml-4" style=" width: 400px;">
      <h3 class="pl-3">Ready to earn?</h3>
      <%= render 'form', horse: @horse %>
    </div>
</div>

app/views/horses/search.html.erb
<div class="wrapper wrapper-search" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url(<%= image_path 'horsebetter.jpg' %>)">
  <div class="searchforn p-3 ml-4">
    <%= render 'searchform', horses: @horses%>
  </div>
</div>

app/views/horses/show.html.erb
<div class="banner" style="background-image: url('<%= cl_image_path @horse.image, crop: :scale %>')">
<!-- <div class="horse-photo">
      <%= cl_image_tag @horse.image %>
    </div> -->
  </div>

<!-- <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="horse-photo carousel-item active">
      <%= cl_image_tag @horse.image %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> -->



<div class="container d-flex mt-4">

  <div class="container-left flex-grow-1">
    <h3><strong><%= @horse.name %></strong></h3>
    <br>
    <div class="info-perso">
      <div>
        <h5 style="line-height: 0.5;"><strong>Owner</strong></h5>
        <p><%= @horse.user.email %></p>
      </div>
    </div>
      <h5 style="line-height: 0.5;"><strong>Description</strong></h5>
      <p><%= @horse.description %></p>
      <h5 style="line-height: 0.5;"><strong>Price</strong></h5>
      <p><%= @horse.price %> € / day</p>
  </div>

  <div class="container-right">
    <% if current_user == @horse.user %>
    <div></div>
    <%else %>
    <div class="wrapper-form p-4 ml-1 mb-5" style=" width: 400px;">
    <div class=“booking-form” style="padding: 20px">
      <h2 style="padding-bottom: 15px;">Book horse</h2>
      <%= simple_form_for [@horse, @booking] do |f|%>
      <%= f.input :start_date, class: 'simple_form_input' %>
      <%= f.input :end_date, class: 'simple_form_input' %>
      <div class="form-actions btn-block mb-3">
       <%= f.submit 'Book', class: 'btn btn-book btn-block'%>
       <% end %>
     </div>
   </div>
 </div>
<% end %>
  </div>
</div>


<div class="container content-container">

      <div class="location-title mb-2 ">
        <h6>Stationed in
          <%= @horse.location %></h6>
        </div>
        <%#= image_tag "https://s3.eestatic.com/2017/10/11/social/La_Jungla_253487245_50033619_1024x576.jpg", alt: "map", class: "map mt-4" %>
        <!--       <p class="mt-2">Exact location information is provided after a booking is confirmed.</p> -->
        <div
        id="map" class="show-map"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

  </div>

  <div class="container show-buttons mb-3">

    <% if current_user == @horse.user %>

    <div class="show-buttons mb-3">
      <%= link_to 'Delete Horse', horse_path(@horse), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-dark mr-2 mt-3"%>
      <%= link_to 'Edit horse', edit_horse_path(@horse), class: "btn btn-outline-dark mt-3"  %>
    </div>
  </div>

  <%else %>

 <div class="back-btn">
    <%= link_to 'Back', horses_path, class: "btn btn-outline-dark mt-3" %>
  </div>

 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Grab a Horse</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <div class="main">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </div>
    <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
 <!--  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
 -->
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
  <span><strong>Yay!</strong> 🎉 you successfully signed in to our service. </span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2019 MyFam, Inc. All rights reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-white bg-white" style="border-bottom: 1px solid lightgrey; color: rgb(72, 72, 72);">
  <%= link_to root_path(@horse) do %>
  <h5 class="btn" style="font-size: 16px">
    <i class="fas fa-horse mb-0 mr-2" style="color: #EE6055; font-size: 24px"></i>GRAB A HORSE
  </h5>
  <% end %>
  <div class="navbar right">
    <%= link_to "Search", root_path, class: "btn"%>
    <%= link_to "List a horse", new_horse_path, class: "btn" %>
    <% if user_signed_in? == false %>
    <%= link_to "Login", new_user_session_path, class: "btn"%>
    <% else %>
    <%= link_to "Dashboard", dashboard_path, class: "btn" %>
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn"%>
    <% end %>
  </div>
</nav>